import type { ProviderModelInfo } from '../../types'
import { ModelProviderEnum, ModelProviderType } from '../../types'
import { defineProvider } from '../registry'
import {
  createOpenCodeModel,
  defineOpenCodeModelClasses,
  type OpenCodeApiStyle,
  type OpenCodeRoutingRules,
  resolveOpenCodeApiStyle,
} from './opencode-shared'

// OpenCode Zen is the pay-as-you-go tier of the same console as OpenCode Go, with the full
// catalog (GPT / Claude / Gemini / Grok plus open models). API-key auth only
// (https://opencode.ai/auth); there is no official OAuth. Requests go to /zen/v1 and are
// routed by model id across four surfaces: Gemini uses the Google generative API,
// Claude / Qwen use Anthropic Messages, GPT / Grok / Muse Spark use Responses, and
// everything else uses Chat Completions.

export const OPENCODE_ZEN_API_HOST = 'https://opencode.ai/zen/v1'
export const OPENCODE_ZEN_AUTH_URL = 'https://opencode.ai/auth'
export const OPENCODE_ZEN_DOCS_URL = 'https://opencode.ai/docs/zen/'
export const OPENCODE_ZEN_MODELS_URL = 'https://opencode.ai/zen/v1/models'

const ROUTING_RULES: OpenCodeRoutingRules = {
  google: ['gemini-'],
  anthropic: ['claude-', 'qwen3.'],
  responses: ['gpt-', 'grok-', 'muse-spark'],
}

export function getOpenCodeZenApiStyle(modelId: string): OpenCodeApiStyle {
  return resolveOpenCodeApiStyle(modelId, ROUTING_RULES)
}

export function applyOpenCodeZenModelMetadata(model: ProviderModelInfo): ProviderModelInfo {
  return {
    ...model,
    // Always overwrite: getModel() may stamp the provider type (`openai`) before
    // createModel runs, which would otherwise pin Claude/Gemini onto the wrong surface.
    apiStyle: getOpenCodeZenApiStyle(model.modelId),
  }
}

const MODEL_CLASSES = defineOpenCodeModelClasses('OpenCode Zen', (models) => models.map(applyOpenCodeZenModelMetadata))

const DEFAULT_MODELS: ProviderModelInfo[] = [
  {
    modelId: 'gpt-5.6-sol',
    nickname: 'GPT-5.6 Sol',
    apiStyle: 'openai-responses',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 1_050_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'gpt-5.6-terra',
    nickname: 'GPT-5.6 Terra',
    apiStyle: 'openai-responses',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 1_050_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'gpt-5.6-luna',
    nickname: 'GPT-5.6 Luna',
    apiStyle: 'openai-responses',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 1_050_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'gpt-5.5',
    nickname: 'GPT-5.5',
    apiStyle: 'openai-responses',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 1_050_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'gpt-5.5-pro',
    nickname: 'GPT-5.5 Pro',
    apiStyle: 'openai-responses',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 1_050_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'gpt-5.4',
    nickname: 'GPT-5.4',
    apiStyle: 'openai-responses',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 1_050_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'gpt-5.4-pro',
    nickname: 'GPT-5.4 Pro',
    apiStyle: 'openai-responses',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 1_050_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'gpt-5.4-mini',
    nickname: 'GPT-5.4 Mini',
    apiStyle: 'openai-responses',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 400_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'gpt-5.4-nano',
    nickname: 'GPT-5.4 Nano',
    apiStyle: 'openai-responses',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 400_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'gpt-5.3-codex-spark',
    nickname: 'GPT-5.3 Codex Spark',
    apiStyle: 'openai-responses',
    capabilities: ['tool_use', 'reasoning'],
    contextWindow: 128_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'gpt-5.3-codex',
    nickname: 'GPT-5.3 Codex',
    apiStyle: 'openai-responses',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 400_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'gpt-5.2',
    nickname: 'GPT-5.2',
    apiStyle: 'openai-responses',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 400_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'gpt-5.2-codex',
    nickname: 'GPT-5.2 Codex',
    apiStyle: 'openai-responses',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 400_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'gpt-5.1',
    nickname: 'GPT-5.1',
    apiStyle: 'openai-responses',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 400_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'gpt-5.1-codex-max',
    nickname: 'GPT-5.1 Codex Max',
    apiStyle: 'openai-responses',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 400_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'gpt-5.1-codex',
    nickname: 'GPT-5.1 Codex',
    apiStyle: 'openai-responses',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 400_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'gpt-5.1-codex-mini',
    nickname: 'GPT-5.1 Codex Mini',
    apiStyle: 'openai-responses',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 400_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'gpt-5',
    nickname: 'GPT-5',
    apiStyle: 'openai-responses',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 400_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'gpt-5-codex',
    nickname: 'GPT-5 Codex',
    apiStyle: 'openai-responses',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 400_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'gpt-5-nano',
    nickname: 'GPT-5 Nano',
    apiStyle: 'openai-responses',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 400_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'grok-build-0.1',
    nickname: 'Grok Build 0.1',
    apiStyle: 'openai-responses',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 256_000,
    maxOutput: 256_000,
  },
  {
    modelId: 'grok-4.6',
    nickname: 'Grok 4.6',
    apiStyle: 'openai-responses',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 500_000,
    maxOutput: 500_000,
  },
  {
    modelId: 'grok-4.5',
    nickname: 'Grok 4.5',
    apiStyle: 'openai-responses',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 500_000,
    maxOutput: 500_000,
  },
  {
    modelId: 'muse-spark-1.2',
    nickname: 'Muse Spark 1.2',
    apiStyle: 'openai-responses',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 1_048_576,
    maxOutput: 131_072,
  },
  {
    modelId: 'muse-spark-1.2-contributor-free',
    nickname: 'Muse Spark 1.2 Free',
    apiStyle: 'openai-responses',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 1_048_576,
    maxOutput: 131_072,
  },
  {
    modelId: 'claude-fable-5',
    nickname: 'Claude Fable 5',
    apiStyle: 'anthropic',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 1_000_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'claude-opus-5',
    nickname: 'Claude Opus 5',
    apiStyle: 'anthropic',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 1_000_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'claude-opus-4-8',
    nickname: 'Claude Opus 4.8',
    apiStyle: 'anthropic',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 1_000_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'claude-opus-4-7',
    nickname: 'Claude Opus 4.7',
    apiStyle: 'anthropic',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 1_000_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'claude-opus-4-6',
    nickname: 'Claude Opus 4.6',
    apiStyle: 'anthropic',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 1_000_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'claude-opus-4-5',
    nickname: 'Claude Opus 4.5',
    apiStyle: 'anthropic',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 200_000,
    maxOutput: 64_000,
  },
  {
    modelId: 'claude-sonnet-5',
    nickname: 'Claude Sonnet 5',
    apiStyle: 'anthropic',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 1_000_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'claude-sonnet-4-6',
    nickname: 'Claude Sonnet 4.6',
    apiStyle: 'anthropic',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 1_000_000,
    maxOutput: 64_000,
  },
  {
    modelId: 'claude-sonnet-4-5',
    nickname: 'Claude Sonnet 4.5',
    apiStyle: 'anthropic',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 1_000_000,
    maxOutput: 64_000,
  },
  {
    modelId: 'claude-sonnet-4',
    nickname: 'Claude Sonnet 4',
    apiStyle: 'anthropic',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 1_000_000,
    maxOutput: 64_000,
  },
  {
    modelId: 'claude-haiku-4-5',
    nickname: 'Claude Haiku 4.5',
    apiStyle: 'anthropic',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 200_000,
    maxOutput: 64_000,
  },
  {
    modelId: 'qwen3.6-plus',
    nickname: 'Qwen3.6 Plus',
    apiStyle: 'anthropic',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 262_144,
    maxOutput: 65_536,
  },
  {
    modelId: 'qwen3.5-plus',
    nickname: 'Qwen3.5 Plus',
    apiStyle: 'anthropic',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 262_144,
    maxOutput: 65_536,
  },
  {
    modelId: 'gemini-3.6-flash',
    nickname: 'Gemini 3.6 Flash',
    apiStyle: 'google',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 1_048_576,
    maxOutput: 65_536,
  },
  {
    modelId: 'gemini-3.7-flash',
    nickname: 'Gemini 3.7 Flash',
    apiStyle: 'google',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 1_048_576,
    maxOutput: 65_536,
  },
  {
    modelId: 'gemini-3.5-flash-lite',
    nickname: 'Gemini 3.5 Flash Lite',
    apiStyle: 'google',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 1_048_576,
    maxOutput: 65_536,
  },
  {
    modelId: 'gemini-3.5-flash',
    nickname: 'Gemini 3.5 Flash',
    apiStyle: 'google',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 1_048_576,
    maxOutput: 65_536,
  },
  {
    modelId: 'gemini-3.1-pro',
    nickname: 'Gemini 3.1 Pro Preview',
    apiStyle: 'google',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 1_048_576,
    maxOutput: 65_536,
  },
  {
    modelId: 'gemini-3-flash',
    nickname: 'Gemini 3 Flash',
    apiStyle: 'google',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 1_048_576,
    maxOutput: 65_536,
  },
  {
    modelId: 'deepseek-v4-pro',
    nickname: 'DeepSeek V4 Pro',
    apiStyle: 'openai',
    capabilities: ['tool_use', 'reasoning'],
    contextWindow: 1_000_000,
    maxOutput: 384_000,
  },
  {
    modelId: 'deepseek-v4-flash',
    nickname: 'DeepSeek V4 Flash',
    apiStyle: 'openai',
    capabilities: ['tool_use', 'reasoning'],
    contextWindow: 1_000_000,
    maxOutput: 384_000,
  },
  {
    modelId: 'glm-5.2',
    nickname: 'GLM-5.2',
    apiStyle: 'openai',
    capabilities: ['tool_use', 'reasoning'],
    contextWindow: 1_000_000,
    maxOutput: 131_072,
  },
  {
    modelId: 'glm-5.1',
    nickname: 'GLM-5.1',
    apiStyle: 'openai',
    capabilities: ['tool_use', 'reasoning'],
    contextWindow: 204_800,
    maxOutput: 131_072,
  },
  {
    modelId: 'glm-5',
    nickname: 'GLM-5',
    apiStyle: 'openai',
    capabilities: ['tool_use', 'reasoning'],
    contextWindow: 204_800,
    maxOutput: 131_072,
  },
  {
    modelId: 'minimax-m3',
    nickname: 'MiniMax-M3',
    apiStyle: 'openai',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 512_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'minimax-m2.7',
    nickname: 'MiniMax-M2.7',
    apiStyle: 'openai',
    capabilities: ['tool_use', 'reasoning'],
    contextWindow: 204_800,
    maxOutput: 131_072,
  },
  {
    modelId: 'minimax-m2.5',
    nickname: 'MiniMax-M2.5',
    apiStyle: 'openai',
    capabilities: ['tool_use', 'reasoning'],
    contextWindow: 204_800,
    maxOutput: 131_072,
  },
  {
    modelId: 'kimi-k3',
    nickname: 'Kimi K3',
    apiStyle: 'openai',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 1_048_576,
    maxOutput: 131_072,
  },
  {
    modelId: 'kimi-k2.7-code',
    nickname: 'Kimi K2.7 Code',
    apiStyle: 'openai',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 262_144,
    maxOutput: 262_144,
  },
  {
    modelId: 'kimi-k2.6',
    nickname: 'Kimi K2.6',
    apiStyle: 'openai',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 262_144,
    maxOutput: 65_536,
  },
  {
    modelId: 'kimi-k2.5',
    nickname: 'Kimi K2.5',
    apiStyle: 'openai',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 262_144,
    maxOutput: 65_536,
  },
  {
    modelId: 'big-pickle',
    nickname: 'Big Pickle',
    apiStyle: 'openai',
    capabilities: ['tool_use', 'reasoning'],
    contextWindow: 200_000,
    maxOutput: 32_000,
  },
  {
    modelId: 'deepseek-v4-flash-free',
    nickname: 'DeepSeek V4 Flash Free',
    apiStyle: 'openai',
    capabilities: ['tool_use', 'reasoning'],
    contextWindow: 200_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'mimo-v2.5-free',
    nickname: 'MiMo V2.5 Free',
    apiStyle: 'openai',
    capabilities: ['vision', 'tool_use', 'reasoning'],
    contextWindow: 200_000,
    maxOutput: 32_000,
  },
  {
    modelId: 'hy3-free',
    nickname: 'Hy3 Free',
    apiStyle: 'openai',
    capabilities: ['tool_use', 'reasoning'],
    contextWindow: 190_000,
    maxOutput: 64_000,
  },
  {
    modelId: 'nemotron-3-ultra-free',
    nickname: 'Nemotron 3 Ultra Free',
    apiStyle: 'openai',
    capabilities: ['tool_use', 'reasoning'],
    contextWindow: 1_000_000,
    maxOutput: 128_000,
  },
  {
    modelId: 'nemotron-3.5-lightning-free',
    nickname: 'Nemotron 3.5 Lightning Free',
    apiStyle: 'openai',
    capabilities: ['tool_use', 'reasoning'],
    contextWindow: 262_144,
    maxOutput: 262_144,
  },
  {
    modelId: 'laguna-s-2.1-free',
    nickname: 'Laguna S 2.1 Free',
    apiStyle: 'openai',
    capabilities: ['tool_use', 'reasoning'],
    contextWindow: 256_000,
    maxOutput: 32_000,
  },
]

export const opencodeZenProvider = defineProvider({
  id: ModelProviderEnum.OpenCodeZen,
  name: 'OpenCode Zen',
  type: ModelProviderType.OpenAI,
  urls: {
    website: 'https://opencode.ai',
    apiKey: OPENCODE_ZEN_AUTH_URL,
    docs: OPENCODE_ZEN_DOCS_URL,
    models: OPENCODE_ZEN_MODELS_URL,
  },
  defaultSettings: {
    apiHost: OPENCODE_ZEN_API_HOST,
    models: DEFAULT_MODELS,
  },
  createModel: (config) =>
    createOpenCodeModel(config, {
      classes: MODEL_CLASSES,
      defaultApiHost: OPENCODE_ZEN_API_HOST,
      defaultModels: DEFAULT_MODELS,
      getApiStyle: getOpenCodeZenApiStyle,
    }),
  getDisplayName: (modelId, providerSettings) => {
    return `OpenCode Zen (${providerSettings?.models?.find((m) => m.modelId === modelId)?.nickname || modelId})`
  },
})
