import { ModelProviderEnum, ModelProviderType } from '../../types'
import { defineProvider } from '../registry'
import OpenRouter from './models/openrouter'

export const openRouterProvider = defineProvider({
  id: ModelProviderEnum.OpenRouter,
  name: 'OpenRouter',
  type: ModelProviderType.OpenAI,
  modelsDevProviderId: 'openrouter',
  curatedModelIds: [
    'openai/gpt-5.6-sol',
    'openai/gpt-5.6-terra',
    'openai/gpt-5.6-luna',
    'anthropic/claude-fable-5',
    'anthropic/claude-opus-5',
    'anthropic/claude-sonnet-5',
    'google/gemini-3.7-flash',
    'x-ai/grok-4.6',
    'deepseek/deepseek-v4-pro',
    'deepseek/deepseek-v4-flash',
    'moonshotai/kimi-k3',
    'minimax/minimax-m3',
    'z-ai/glm-5.2',
    'qwen/qwen3.7-plus',
    'anthropic/claude-opus-4.8',
    'anthropic/claude-sonnet-4.6',
    'google/gemini-3.5-flash',
    'google/gemini-3.1-pro-preview',
    'google/gemini-2.5-flash-lite',
    'openai/gpt-5.4',
    'openai/gpt-5.4-mini',
    'openai/o4-mini',
    'x-ai/grok-4.3',
    'moonshotai/kimi-k2.6',
    'openrouter/free',
  ],
  urls: {
    website: 'https://openrouter.ai/',
  },
  defaultSettings: {
    apiHost: 'https://openrouter.ai/api/v1',
    models: [
      {
        modelId: 'openai/gpt-5.6-sol',
        nickname: 'GPT-5.6 Sol',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_050_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'openai/gpt-5.6-terra',
        nickname: 'GPT-5.6 Terra',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_050_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'openai/gpt-5.6-luna',
        nickname: 'GPT-5.6 Luna',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_050_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'anthropic/claude-fable-5',
        nickname: 'Claude Fable 5',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_000_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'anthropic/claude-opus-5',
        nickname: 'Claude Opus 5',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_000_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'anthropic/claude-sonnet-5',
        nickname: 'Claude Sonnet 5',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_000_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'google/gemini-3.7-flash',
        nickname: 'Gemini 3.7 Flash',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_048_576,
        maxOutput: 65_536,
      },
      {
        modelId: 'x-ai/grok-4.6',
        nickname: 'Grok 4.6',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 500_000,
      },
      {
        modelId: 'deepseek/deepseek-v4-pro',
        nickname: 'DeepSeek V4 Pro',
        capabilities: ['tool_use', 'reasoning'],
        contextWindow: 1_048_576,
        maxOutput: 384_000,
      },
      {
        modelId: 'deepseek/deepseek-v4-flash',
        nickname: 'DeepSeek V4 Flash',
        capabilities: ['tool_use', 'reasoning'],
        contextWindow: 1_048_576,
        maxOutput: 384_000,
      },
      {
        modelId: 'moonshotai/kimi-k3',
        nickname: 'Kimi K3',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_048_576,
      },
      {
        modelId: 'minimax/minimax-m3',
        nickname: 'MiniMax M3',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_048_576,
        maxOutput: 512_000,
      },
      {
        modelId: 'z-ai/glm-5.2',
        nickname: 'GLM 5.2',
        capabilities: ['tool_use', 'reasoning'],
        contextWindow: 1_048_576,
        maxOutput: 131_072,
      },
      {
        modelId: 'qwen/qwen3.7-plus',
        nickname: 'Qwen 3.7 Plus',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_000_000,
        maxOutput: 65_536,
      },
      {
        modelId: 'anthropic/claude-opus-4.8',
        nickname: 'Claude Opus 4.8',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_000_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'anthropic/claude-sonnet-4.6',
        nickname: 'Claude Sonnet 4.6',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_000_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'google/gemini-3.5-flash',
        nickname: 'Gemini 3.5 Flash',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_048_576,
        maxOutput: 65_536,
      },
      {
        modelId: 'google/gemini-3.1-pro-preview',
        nickname: 'Gemini 3.1 Pro',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_048_576,
        maxOutput: 65_536,
      },
      {
        modelId: 'google/gemini-2.5-flash-lite',
        nickname: 'Gemini 2.5 Flash Lite',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_048_576,
        maxOutput: 65_535,
      },
      {
        modelId: 'openai/gpt-5.4',
        nickname: 'GPT-5.4',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_050_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'openai/gpt-5.4-mini',
        nickname: 'GPT-5.4 Mini',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 400_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'openai/o4-mini',
        nickname: 'o4 Mini',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 200_000,
        maxOutput: 100_000,
      },
      {
        modelId: 'x-ai/grok-4.3',
        nickname: 'Grok 4.3',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_000_000,
      },
      {
        modelId: 'moonshotai/kimi-k2.6',
        nickname: 'Kimi K2.6',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 262_144,
        maxOutput: 262_144,
      },
      {
        modelId: 'openrouter/free',
        nickname: 'Free Models Router',
      },
    ],
  },
  createModel: (config) => {
    return new OpenRouter(
      {
        apiKey: config.effectiveApiKey,
        model: config.model,
        temperature: config.settings.temperature,
        topP: config.settings.topP,
        maxOutputTokens: config.settings.maxTokens,
        stream: config.settings.stream,
      },
      config.dependencies
    )
  },
  getDisplayName: (modelId, providerSettings) => {
    return `OpenRouter API (${providerSettings?.models?.find((m) => m.modelId === modelId)?.nickname || modelId})`
  },
})
