import { ModelProviderEnum, ModelProviderType } from '../../types'
import { defineProvider } from '../registry'
import VercelAIGateway from './models/vercel-ai-gateway'

export const vercelAIGatewayProvider = defineProvider({
  id: ModelProviderEnum.VercelAIGateway,
  name: 'Vercel AI Gateway',
  type: ModelProviderType.OpenAI,
  curatedModelIds: [
    'openai/gpt-5.6-sol',
    'openai/gpt-5.6-terra',
    'openai/gpt-5.6-luna',
    'anthropic/claude-fable-5',
    'anthropic/claude-opus-5',
    'anthropic/claude-sonnet-5',
    'google/gemini-3.7-flash',
    'xai/grok-4.6',
    'deepseek/deepseek-v4-pro',
    'deepseek/deepseek-v4-flash',
    'moonshotai/kimi-k3',
    'minimax/minimax-m3',
    'zai/glm-5.2',
    'alibaba/qwen3.7-plus',
    'google/gemini-3.5-flash',
    'google/gemini-3.1-pro-preview',
    'google/gemini-2.5-flash-lite',
    'anthropic/claude-opus-4.6',
    'anthropic/claude-sonnet-4.6',
    'anthropic/claude-haiku-4.5',
    'openai/gpt-5.4',
    'openai/gpt-5.4-mini',
    'xai/grok-4.1-fast-non-reasoning',
    'minimax/minimax-m2.7',
    'minimax/minimax-m2.5',
    'moonshotai/kimi-k2.6',
    'kwaipilot/kat-coder-pro-v2',
  ],
  urls: {
    website: 'https://vercel.com/ai-gateway',
    docs: 'https://vercel.com/docs/ai-gateway',
    models: 'https://vercel.com/ai-gateway/models',
  },
  defaultSettings: {
    apiHost: 'https://ai-gateway.vercel.sh/v3/ai',
    models: [
      {
        modelId: 'openai/gpt-5.6-sol',
        nickname: 'GPT-5.6 Sol',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_050_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'openai/gpt-5.6-terra',
        nickname: 'GPT-5.6 Terra',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_050_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'openai/gpt-5.6-luna',
        nickname: 'GPT-5.6 Luna',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_050_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'anthropic/claude-fable-5',
        nickname: 'Claude Fable 5',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_000_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'anthropic/claude-opus-5',
        nickname: 'Claude Opus 5',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_000_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'anthropic/claude-sonnet-5',
        nickname: 'Claude Sonnet 5',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_000_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'google/gemini-3.7-flash',
        nickname: 'Gemini 3.7 Flash',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_048_576,
        maxOutput: 65_536,
      },
      {
        modelId: 'xai/grok-4.6',
        nickname: 'Grok 4.6',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 500_000,
        maxOutput: 500_000,
      },
      {
        modelId: 'deepseek/deepseek-v4-pro',
        nickname: 'DeepSeek V4 Pro',
        capabilities: ['tool_use', 'reasoning'],
        contextWindow: 1_048_576,
        maxOutput: 384_000,
      },
      {
        modelId: 'deepseek/deepseek-v4-flash',
        nickname: 'DeepSeek V4 Flash',
        capabilities: ['tool_use', 'reasoning'],
        contextWindow: 1_048_576,
        maxOutput: 384_000,
      },
      {
        modelId: 'moonshotai/kimi-k3',
        nickname: 'Kimi K3',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_048_576,
        maxOutput: 131_072,
      },
      {
        modelId: 'minimax/minimax-m3',
        nickname: 'MiniMax M3',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_048_576,
        maxOutput: 1_048_576,
      },
      {
        modelId: 'zai/glm-5.2',
        nickname: 'GLM 5.2',
        capabilities: ['tool_use', 'reasoning'],
        contextWindow: 1_048_576,
        maxOutput: 131_072,
      },
      {
        modelId: 'alibaba/qwen3.7-plus',
        nickname: 'Qwen 3.7 Plus',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_000_000,
        maxOutput: 65_536,
      },
      {
        modelId: 'google/gemini-3.5-flash',
        nickname: 'Gemini 3.5 Flash',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_000_000,
        maxOutput: 64_000,
      },
      {
        modelId: 'google/gemini-3.1-pro-preview',
        nickname: 'Gemini 3.1 Pro',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_000_000,
        maxOutput: 64_000,
      },
      {
        modelId: 'google/gemini-2.5-flash-lite',
        nickname: 'Gemini 2.5 Flash Lite',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_048_576,
        maxOutput: 65_536,
      },
      {
        modelId: 'anthropic/claude-opus-4.6',
        nickname: 'Claude Opus 4.6',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_000_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'anthropic/claude-sonnet-4.6',
        nickname: 'Claude Sonnet 4.6',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_000_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'anthropic/claude-haiku-4.5',
        nickname: 'Claude Haiku 4.5',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 200_000,
        maxOutput: 64_000,
      },
      {
        modelId: 'openai/gpt-5.4',
        nickname: 'GPT-5.4',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 1_050_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'openai/gpt-5.4-mini',
        nickname: 'GPT-5.4 Mini',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 400_000,
        maxOutput: 128_000,
      },
      {
        modelId: 'xai/grok-4.1-fast-non-reasoning',
        nickname: 'Grok 4.1 Fast',
        capabilities: ['tool_use', 'vision'],
        contextWindow: 1_000_000,
        maxOutput: 1_000_000,
      },
      {
        modelId: 'minimax/minimax-m2.7',
        nickname: 'MiniMax M2.7',
        capabilities: ['tool_use', 'reasoning'],
        contextWindow: 204_800,
        maxOutput: 131_000,
      },
      {
        modelId: 'minimax/minimax-m2.5',
        nickname: 'MiniMax M2.5',
        capabilities: ['tool_use', 'reasoning'],
        contextWindow: 204_800,
        maxOutput: 131_000,
      },
      {
        modelId: 'moonshotai/kimi-k2.6',
        nickname: 'Kimi K2.6',
        capabilities: ['tool_use', 'reasoning', 'vision'],
        contextWindow: 262_000,
        maxOutput: 262_000,
      },
      {
        modelId: 'kwaipilot/kat-coder-pro-v2',
        nickname: 'KAT Coder Pro V2',
        capabilities: ['tool_use'],
        contextWindow: 256_000,
        maxOutput: 256_000,
      },
    ],
  },
  createModel: (config) => {
    return new VercelAIGateway(
      {
        apiKey: config.effectiveApiKey,
        apiHost: config.formattedApiHost ? config.formattedApiHost.replace(/\/$/, '') : undefined,
        model: config.model,
        temperature: config.settings.temperature,
        topP: config.settings.topP,
        maxOutputTokens: config.settings.maxTokens,
        useProxy: config.providerSetting.useProxy,
        stream: config.settings.stream,
      },
      config.dependencies
    )
  },
  getDisplayName: (modelId, providerSettings) => {
    return `Vercel AI Gateway (${providerSettings?.models?.find((m) => m.modelId === modelId)?.nickname || modelId})`
  },
})
