/** Public, host-neutral API for Chatbox application and generation logic. */

export type { ChatStreamOptions, ModelInterface, ModelStreamPart } from '@shared/models/types'
export type {
  CompactionPoint,
  Config,
  Language,
  Message,
  Session,
  SessionMeta,
  SessionMetaPage,
  SessionMetaRecord,
  SessionSettings,
  SessionThread,
  Settings,
  Updater,
} from '@shared/types'
export {
  type AttachmentAnalysis,
  type AttachmentAnalysisPort,
  type AttachmentParserPort,
  type AttachmentPreparationOptions,
  AttachmentService,
  type AttachmentServiceDependencies,
  encodeBase64,
  type ParsedAttachmentContent,
  type PickedAsset,
  type PickedAssetContentPort,
  type PreparedAttachment,
} from './application/attachments'
export {
  buildCompactionCommitPatch,
  type CompactionFailure,
  type CompactionFailureCode,
  type CompactionPolicyPort,
  CompactionService,
  type CompactionServiceOptions,
  type CompactionServiceResult,
  type CompactionSessionPort,
  type CompactionSummaryPort,
  findLastCompactionBoundaryMessage,
  isAutoCompactionEnabled,
} from './application/context'
export { ModelFactory, type ModelFactoryOptions, type ModelResolver } from './application/model'
export {
  assertNoMessageDataUpdate,
  createSessionMetaRecord,
  ForkService,
  getSessionMetadataSnapshot,
  hasSessionMetaFields,
  type NameGenerationSchedulerPort,
  projectSessionMeta,
  type ScheduledNameGeneration,
  type SessionApplicationEvent,
  type SessionDeleteOperation,
  SessionEventBus,
  type SessionEventListener,
  type SessionMetadataUpdate,
  type SessionNameGenerationOptions,
  SessionNamingService,
  type SessionNamingServiceDependencies,
  SessionNotFoundError,
  SessionService,
  type SessionServiceOptions,
  type SessionUseCasePort,
  SessionWriteCoordinator,
  type SessionWriteCoordinatorOptions,
  type SessionWriteOptions,
  type SessionWriteResult,
  ThreadService,
  type ThreadServiceDependencies,
  type UpdateSessionOptions,
} from './application/session'
export { type SettingsListener, SettingsService, type SettingsServiceOptions } from './application/settings'
export {
  AgentModeEntrySchema,
  type BuiltinProviderBaseInfo,
  type ChatboxAILicenseDetail,
  type ChatboxAIPlanType,
  type ClaudeParams,
  type CustomProviderBaseInfo,
  createDefaultSettings,
  DEFAULT_DOCUMENT_PARSER_CONFIG,
  DEFAULT_SYSTEM_PROMPT,
  type DocumentParserConfig,
  DocumentParserConfigSchema,
  type DocumentParserType,
  decodePersistedSettings,
  type ExtensionSettings,
  encodePersistedSettings,
  type GlobalSessionSettings,
  GlobalSessionSettingsSchema,
  type GoogleParams,
  getDefaultDocumentParser,
  type MCPServerConfig,
  type MCPSettings,
  type MCPTransportConfig,
  ModelProviderType,
  mergeSettingsWithDefaults,
  migrateSettings,
  OAuthCredentialsSchema,
  type OpenAIParams,
  type PersistedSettingsEnvelope,
  type ProviderBaseInfo,
  type ProviderInfo,
  type ProviderModelInfo,
  ProviderModelInfoSchema,
  type ProviderOptions,
  ProviderOptionsSchema,
  type ProviderSettings,
  ProviderSettingsSchema,
  SETTINGS_PERSIST_VERSION,
  SessionSettingsSchema,
  type SettingsHostDefaults,
  SettingsSchema,
  type ShortcutName,
  type ShortcutSendValue,
  type ShortcutSetting,
  type ShortcutToggleWindowValue,
  type SkillSettings,
  shortcutSendValues,
  shortcutToggleWindowValues,
  Theme,
  type UnifiedTokenUsageDetail,
} from './domain/settings'
export {
  AGENT_MODE_SUGGESTION_PROMPT,
  type AgentModeSuggestionDecision,
  applyLegacyToolFallback,
  applyPersistentToolCallPause,
  cancelRunningToolCallBatch,
  createInitialState,
  createPausedToolCallExecutionContext,
  describeUserMessageForAgentModeDecision,
  finalizeReasoningDuration,
  finalizeToolCallDuration,
  findLastRetryableToolCallPart,
  findPausedApprovalBatch,
  findPausedToolCallLimitBatch,
  findToolCallPart,
  finishAbortedGeneration,
  finishPausedToolCallContinuation,
  type GenerationAgentModeEntrySource,
  type GenerationAnalyticsPort,
  type GenerationCoordinationPort,
  type GenerationHostPort,
  type GenerationModelContext,
  type GenerationModelFactoryPort,
  type GenerationOperationType,
  type GenerationOptions,
  type GenerationPreparationPort,
  type GenerationPreparationRequest,
  type GenerationRuntimePhase,
  type GenerationRuntimeState,
  GenerationRuntimeStore,
  type GenerationRuntimeStoreOptions,
  GenerationService,
  type GenerationServiceDependencies,
  type GenerationSessionPort,
  type GenerationToolExecutionPort,
  getApprovalTrackingTarget,
  getLastUserMessage,
  getToolCallPause,
  hasPausedToolCallPart,
  isFirstUserTurn,
  isRetryableToolCallStep,
  keepContentPartsThroughToolCall,
  type LegacyCombinedSearchResult,
  type LegacyKnowledgeBaseSearchResult,
  type LegacyToolFallbackDependencies,
  type LegacyToolFallbackOptions,
  type LegacyToolFallbackResult,
  type LegacyWebSearchResult,
  markToolCallPaused,
  type PreparedGeneration,
  parseAgentModeSuggestionDecision,
  processStreamChunk,
  resetSessionGenerationLocksForTests,
  type StreamProcessorCallbacks,
  type StreamProcessorState,
  shouldPersistStreamingChunk,
  TOOL_RESULT_PREVIEW_LENGTH,
  TOOL_RESULT_SIZE_LIMIT,
  ToolCallLimitPausedError,
  updateToolCallPart,
  updateToolCallParts,
  withSessionGenerationLock,
  withToolCallLimitPause,
} from './generation'
export {
  type ApprovalPauseReason,
  hasPendingPauseInteraction,
  isApprovalPauseReason,
  listPendingApprovalToolCalls,
  listPendingPauseInteractions,
  type PendingApprovalToolCall,
  type PendingPauseInteraction,
} from './message-approval'
export {
  type AnalyticsEventValue,
  type AnalyticsPort,
  type AttachmentContentPort,
  type AttachmentDescriptor,
  type BlobStoragePort,
  type KeyValueStoragePort,
  type LoggerPort,
  type LogLevel,
  type ModelFactoryPort,
  type PlatformCapabilitiesPort,
  type PlatformCapability,
  type SessionDataRepositoryPort,
  type SessionMetaRepositoryPort,
  SessionRepositoryError,
  type SessionRepositoryOperation,
  type SessionRepositoryPort,
  type SettingsRepositoryPort,
  type SettingsStoragePort,
  type SettingsUpdate,
} from './ports'
export {
  assertSessionActionAllowed,
  deriveSessionLockState,
  getSessionActionGate,
  getSubmitAvailability,
  IDLE_SESSION_LOCK_STATE,
  isGenerationLocked,
  type SessionAction,
  SessionActionBlockedError,
  type SessionActionBlockReason,
  type SessionActionContext,
  type SessionActionGate,
  type SessionLockState,
  type SubmitAvailability,
  sessionLockStatesEqual,
  shouldShowConcurrentReplyStop,
} from './session/action-gates'
export {
  type AutoTitleAction,
  type AutoTitleSession,
  backfillMissingThreadName,
  buildNameGenerationAttemptKey,
  DEFAULT_INBOX_SESSION_ID,
  DEFAULT_INBOX_SESSION_NAME,
  getCurrentThreadNamingIdentity,
  isDefaultInboxSession,
  isNameGenerationAttemptKeyForSession,
  type NameGenerationKind,
  resolveAutoTitleAction,
  sanitizeGeneratedSessionName,
  shouldBackfillThreadName,
  type ThreadNamingIdentitySession,
  UNTITLED_SESSION_NAME,
} from './session/auto-title'
export {
  countCancellableGeneratingAssistantMessages,
  getConversationMessages,
  getCurrentConversationMessages,
  getGenerationControlMessages,
  getReachableSessionMessages,
  isCancellableGeneratingAssistantMessage,
} from './session/generation-state'
export {
  hasContentForAutoTitle,
  hasSuccessfulUserAssistantTurn,
  isSuccessfulAssistantReply,
} from './session/message-success'
