import { randomUUID } from 'node:crypto'
import { existsSync, lstatSync, mkdirSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { afterEach, beforeEach, describe, expect, test, vi } from 'vitest'

const { USER_DATA, blobs, getStoreBlob } = vi.hoisted(() => {
  const os = require('node:os') as typeof import('node:os')
  const p = require('node:path') as typeof import('node:path')
  const blobs = new Map<string, string>()
  return {
    USER_DATA: p.join(os.tmpdir(), `chatbox-copy-blob-userdata-${process.pid}`),
    blobs,
    getStoreBlob: vi.fn(async (key: string) => blobs.get(key) ?? null),
  }
})

vi.mock('electron', () => ({ app: { isPackaged: false, getPath: () => USER_DATA } }))
vi.mock('../util', () => ({
  getLogger: () => ({ info: vi.fn(), debug: vi.fn(), warn: vi.fn(), error: vi.fn() }),
}))
vi.mock('../store-node', () => ({
  getStoreBlob: (key: string) => getStoreBlob(key),
}))

import { sandboxAttachmentRelPath } from '../../shared/sandbox/attachment-path'
import { ATTACHMENT_SEED_MANIFEST_NAME } from './attachment-seed'
import { copyBlobToSandbox, initSandbox, resetSandbox, seedBlobsToSandbox } from './manager'

describe('copyBlobToSandbox attachment seeding', () => {
  let sessionId: string
  let workDir: string

  beforeEach(async () => {
    vi.stubEnv('CHATBOX_BUILD_TARGET', 'harmony_app')
    blobs.clear()
    getStoreBlob.mockClear()
    sessionId = `copy-blob-${randomUUID()}`
    workDir = path.join(tmpdir(), 'chatbox-sandbox-copy-blob', sessionId)
    mkdirSync(workDir, { recursive: true })
    await expect(initSandbox(workDir, sessionId)).resolves.toMatchObject({ success: true })
  })

  afterEach(async () => {
    await resetSandbox(sessionId)
    rmSync(workDir, { recursive: true, force: true })
    rmSync(USER_DATA, { recursive: true, force: true })
    vi.unstubAllEnvs()
  })

  test('does not replace an identity-path file after that attachment was seeded', async () => {
    blobs.set('blob-v1', 'original upload')
    const dest = sandboxAttachmentRelPath('report.html', 'blob-v1')
    await copyBlobToSandbox('blob-v1', dest, sessionId)
    writeFileSync(path.join(workDir, dest), 'model edited version', 'utf-8')

    const second = await copyBlobToSandbox('blob-v1', dest, sessionId)
    expect(second.success).toBe(true)
    expect(readFileSync(path.join(workDir, dest), 'utf-8')).toBe('model edited version')
  })

  test('does not replace a same-named file after the original attachment was seeded', async () => {
    blobs.set('blob-v1', 'original upload')
    const first = await copyBlobToSandbox('blob-v1', 'report.html', sessionId)
    expect(first.success).toBe(true)
    writeFileSync(path.join(workDir, 'report.html'), 'model edited version', 'utf-8')

    const second = await copyBlobToSandbox('blob-v1', 'report.html', sessionId)
    expect(second.success).toBe(true)
    expect(readFileSync(path.join(workDir, 'report.html'), 'utf-8')).toBe('model edited version')
  })

  test('writes a colliding same-named upload beside the existing file', async () => {
    blobs.set('blob-v1', 'original upload')
    blobs.set('blob-v2', 'second upload')
    await copyBlobToSandbox('blob-v1', 'report.html', sessionId)
    writeFileSync(path.join(workDir, 'report.html'), 'model edited version', 'utf-8')

    const second = await copyBlobToSandbox('blob-v2', 'report.html', sessionId)
    const relocated = sandboxAttachmentRelPath('report.html', 'blob-v2')
    expect(second.success).toBe(true)
    expect(readFileSync(path.join(workDir, 'report.html'), 'utf-8')).toBe('model edited version')
    expect(readFileSync(path.join(workDir, relocated), 'utf-8')).toBe('second upload')
  })

  test('keeps two same-named uploads when seeded to identity paths', async () => {
    blobs.set('blob-a', 'first report')
    blobs.set('blob-b', 'second report')
    const destA = sandboxAttachmentRelPath('report.html', 'blob-a')
    const destB = sandboxAttachmentRelPath('report.html', 'blob-b')

    const first = await copyBlobToSandbox('blob-a', destA, sessionId)
    const second = await copyBlobToSandbox('blob-b', destB, sessionId)
    expect(first.success).toBe(true)
    expect(second.success).toBe(true)
    expect(readFileSync(path.join(workDir, destA), 'utf-8')).toBe('first report')
    expect(readFileSync(path.join(workDir, destB), 'utf-8')).toBe('second report')
  })

  test('does not clobber a model-created file that was never seeded from an attachment', async () => {
    blobs.set('blob-v1', 'uploaded later')
    writeFileSync(path.join(workDir, 'output.html'), 'generated by model', 'utf-8')

    const result = await copyBlobToSandbox('blob-v1', 'output.html', sessionId)
    const relocated = sandboxAttachmentRelPath('output.html', 'blob-v1')
    expect(result.success).toBe(true)
    expect(readFileSync(path.join(workDir, 'output.html'), 'utf-8')).toBe('generated by model')
    expect(readFileSync(path.join(workDir, relocated), 'utf-8')).toBe('uploaded later')
  })

  test('reconciles a pre-manifest seeded file without replacing a later same-named upload', async () => {
    blobs.set('blob-v1', 'original upload')
    blobs.set('blob-v2', 'second upload')
    // Workdir from before the manifest existed: the seeded file is on disk, no manifest.
    writeFileSync(path.join(workDir, 'report.html'), 'original upload', 'utf-8')

    const reseed = await copyBlobToSandbox('blob-v1', 'report.html', sessionId)
    expect(reseed.success).toBe(true)
    expect(readFileSync(path.join(workDir, 'report.html'), 'utf-8')).toBe('original upload')

    const second = await copyBlobToSandbox('blob-v2', 'report.html', sessionId)
    const relocated = sandboxAttachmentRelPath('report.html', 'blob-v2')
    expect(second.success).toBe(true)
    expect(readFileSync(path.join(workDir, 'report.html'), 'utf-8')).toBe('original upload')
    expect(readFileSync(path.join(workDir, relocated), 'utf-8')).toBe('second upload')
  })

  test('keeps the edited working copy when the manifest entry was lost', async () => {
    blobs.set('blob-v1', 'original upload')
    const dest = sandboxAttachmentRelPath('report.html', 'blob-v1')
    await copyBlobToSandbox('blob-v1', dest, sessionId)
    writeFileSync(path.join(workDir, dest), 'model edited version', 'utf-8')
    // Sidecar deleted by a sandbox task (or lost to a crash between write and record).
    rmSync(path.join(workDir, ATTACHMENT_SEED_MANIFEST_NAME))

    const reseed = await copyBlobToSandbox('blob-v1', dest, sessionId)
    expect(reseed.success).toBe(true)
    expect(readFileSync(path.join(workDir, dest), 'utf-8')).toBe('model edited version')

    // The baseline is restored, so the next reseed skips without touching the file.
    const manifest = JSON.parse(readFileSync(path.join(workDir, ATTACHMENT_SEED_MANIFEST_NAME), 'utf-8')) as Record<
      string,
      string
    >
    expect(Object.values(manifest)).toContain('blob-v1')
    getStoreBlob.mockClear()
    const third = await copyBlobToSandbox('blob-v1', dest, sessionId)
    expect(third.success).toBe(true)
    expect(getStoreBlob).not.toHaveBeenCalled()
    expect(readFileSync(path.join(workDir, dest), 'utf-8')).toBe('model edited version')
  })

  test('never follows a manifest replaced with a symlink by a sandbox task', async (ctx) => {
    blobs.set('blob-v1', 'original upload')
    const outsideTarget = path.join(tmpdir(), `chatbox-outside-${randomUUID()}.txt`)
    writeFileSync(outsideTarget, 'user data outside the sandbox', 'utf-8')
    const manifestPath = path.join(workDir, ATTACHMENT_SEED_MANIFEST_NAME)
    try {
      try {
        symlinkSync(outsideTarget, manifestPath)
      } catch {
        return ctx.skip() // creating file symlinks needs a privilege on Windows
      }

      const result = await copyBlobToSandbox('blob-v1', sandboxAttachmentRelPath('report.html', 'blob-v1'), sessionId)
      expect(result.success).toBe(true)
      // The privileged manifest write must not go through the planted link.
      expect(readFileSync(outsideTarget, 'utf-8')).toBe('user data outside the sandbox')
      expect(lstatSync(manifestPath).isSymbolicLink()).toBe(false)
      const manifest = JSON.parse(readFileSync(manifestPath, 'utf-8')) as Record<string, string>
      expect(Object.values(manifest)).toContain('blob-v1')
    } finally {
      rmSync(outsideTarget, { force: true })
    }
  })

  test('self-heals when the manifest is replaced with a symlink after seeding', async (ctx) => {
    blobs.set('blob-v1', 'original upload')
    const dest = sandboxAttachmentRelPath('report.html', 'blob-v1')
    await copyBlobToSandbox('blob-v1', dest, sessionId)
    writeFileSync(path.join(workDir, dest), 'model edited version', 'utf-8')
    const outsideTarget = path.join(tmpdir(), `chatbox-outside-${randomUUID()}.txt`)
    writeFileSync(outsideTarget, 'user data', 'utf-8')
    const manifestPath = path.join(workDir, ATTACHMENT_SEED_MANIFEST_NAME)
    rmSync(manifestPath)
    try {
      try {
        symlinkSync(outsideTarget, manifestPath)
      } catch {
        return ctx.skip()
      }

      const reseed = await copyBlobToSandbox('blob-v1', dest, sessionId)
      expect(reseed.success).toBe(true)
      expect(readFileSync(path.join(workDir, dest), 'utf-8')).toBe('model edited version')
      expect(readFileSync(outsideTarget, 'utf-8')).toBe('user data')
      expect(lstatSync(manifestPath).isSymbolicLink()).toBe(false)
    } finally {
      rmSync(outsideTarget, { force: true })
    }
  })

  test('concurrent seeding keeps every manifest entry', async () => {
    const names = ['a.txt', 'b.txt', 'c.txt', 'd.txt', 'e.txt']
    for (const name of names) blobs.set(`blob-${name}`, `content of ${name}`)

    const results = await Promise.all(names.map((name) => copyBlobToSandbox(`blob-${name}`, name, sessionId)))
    expect(results.every((r) => r.success)).toBe(true)

    const manifest = JSON.parse(readFileSync(path.join(workDir, ATTACHMENT_SEED_MANIFEST_NAME), 'utf-8')) as Record<
      string,
      string
    >
    expect(Object.keys(manifest).sort()).toEqual(names)
  })

  test('same-named files differing only by case share one seed entry on case-insensitive filesystems', async (ctx) => {
    writeFileSync(path.join(workDir, 'case-probe.txt'), 'probe', 'utf-8')
    const caseInsensitiveFs = existsSync(path.join(workDir, 'CASE-PROBE.TXT'))
    rmSync(path.join(workDir, 'case-probe.txt'))
    if (!caseInsensitiveFs) return ctx.skip()

    blobs.set('blob-v1', 'original upload')
    blobs.set('blob-v2', 'second upload')
    await copyBlobToSandbox('blob-v1', 'Report.html', sessionId)

    const second = await copyBlobToSandbox('blob-v2', 'report.html', sessionId)
    const relocated = sandboxAttachmentRelPath('report.html', 'blob-v2')
    expect(second.success).toBe(true)
    expect(readFileSync(path.join(workDir, 'Report.html'), 'utf-8')).toBe('original upload')
    expect(readFileSync(path.join(workDir, relocated), 'utf-8')).toBe('second upload')
  })

  test('rejects using the seed manifest as a copy target', async () => {
    blobs.set('blob-v1', 'nope')
    const result = await copyBlobToSandbox('blob-v1', ATTACHMENT_SEED_MANIFEST_NAME, sessionId)
    expect(result.success).toBe(false)
    expect(result.error).toMatch(/invalid filename/i)
  })

  test('batch reseed skips already-seeded blobs without reading the store', async () => {
    blobs.set('blob-a', 'first report')
    blobs.set('blob-b', 'second report')
    const destA = sandboxAttachmentRelPath('report.html', 'blob-a')
    const destB = sandboxAttachmentRelPath('notes.txt', 'blob-b')
    const items = [
      { blobKey: 'blob-a', targetFilename: destA },
      { blobKey: 'blob-b', targetFilename: destB },
    ]

    const first = await seedBlobsToSandbox(items, sessionId)
    expect(first.success).toBe(true)
    expect(first.results.every((result) => result.success && !result.skipped)).toBe(true)
    expect(getStoreBlob).toHaveBeenCalledTimes(2)
    writeFileSync(path.join(workDir, destA), 'model edited first', 'utf-8')

    getStoreBlob.mockClear()
    const second = await seedBlobsToSandbox(items, sessionId)
    expect(second.success).toBe(true)
    expect(second.results.every((result) => result.success && result.skipped)).toBe(true)
    expect(getStoreBlob).not.toHaveBeenCalled()
    expect(readFileSync(path.join(workDir, destA), 'utf-8')).toBe('model edited first')
    expect(readFileSync(path.join(workDir, destB), 'utf-8')).toBe('second report')
  })

  test('batch seed copies only the attachments that are not on disk yet', async () => {
    blobs.set('blob-a', 'first report')
    blobs.set('blob-b', 'second report')
    const destA = sandboxAttachmentRelPath('report.html', 'blob-a')
    const destB = sandboxAttachmentRelPath('notes.txt', 'blob-b')
    await seedBlobsToSandbox([{ blobKey: 'blob-a', targetFilename: destA }], sessionId)
    getStoreBlob.mockClear()

    const mixed = await seedBlobsToSandbox(
      [
        { blobKey: 'blob-a', targetFilename: destA },
        { blobKey: 'blob-b', targetFilename: destB },
      ],
      sessionId
    )
    expect(mixed.success).toBe(true)
    expect(mixed.results.find((result) => result.targetFilename === destA)?.skipped).toBe(true)
    expect(mixed.results.find((result) => result.targetFilename === destB)?.skipped).toBe(false)
    expect(getStoreBlob).toHaveBeenCalledTimes(1)
    expect(getStoreBlob).toHaveBeenCalledWith('blob-b')
    expect(readFileSync(path.join(workDir, destB), 'utf-8')).toBe('second report')
  })
})
